import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/globals.css";
import ProviderRedux from "@/lib/client/store/StoreProvider"
const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "700"] });
import { getLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { ThemeProviderWrapper } from "@/lib/client/providers/ThemeProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={roboto.className} >
        <ProviderRedux>
          <NextIntlClientProvider locale={locale}>
            <ThemeProviderWrapper>
              {children}
            </ThemeProviderWrapper>
          </NextIntlClientProvider>
        </ProviderRedux>
      </body>
    </html>
  );
}
